server:
  port: 52001
  servlet:
    context-path: /
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.default_schema: public
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://manny.db.elephantsql.com:5432/nfdkdusg
    username: nfdkdusg
    password: qgy8Yvl1qNib5OOL9Cb8p2Clq8m_kvjI
    hikari:
      maximum-pool-size: 5
    tomcat:
      max-active: 5
