server:
  port: 52001
  servlet:
    context-path: /
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.default_schema: public
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://manny.db.elephantsql.com:5432/pufshxih
    username: pufshxih
    password: yXZZyq-2U45jXYpfICHxHDv2set1Fxtj
